### ISSUE TITLE
[Circle Application] CircleCard component 

### ISSUE THREAD

**Issue by junhoyeo** [dimigoin/dimigoin-front-v2#14]
https://github.com/dimigoin/dimigoin-front/blob/master/app/components/CircleCard.vue

**Comment by uhmseohun** [comment]
개인적으로 신청서도 복잡해져서 모달 안 쓰면 좋을 것 같아요.

**Comment by junhoyeo** [comment]
> 개인적으로 신청서도 복잡해져서 모달 안 쓰면 좋을 것 같아요.

헐 CircleCard가 모달이 아니라 동아리별 카드인 줄 알았네요ㅜㅜㅠ
그런데 신청서 말고 정보랑 영상 조회하거나 할 때는 모달 있으면 편할 거 같긴 한데..

**Comment by uhmseohun** [comment]
아 그건 맞는데 신청서만큼은 개별 페이지로 빼는 게 좋을 것 같아서요😇

**Comment by junhoyeo** [comment]
> 아 그건 맞는데 신청서만큼은 개별 페이지로 빼는 게 좋을 것 같아서요😇

그러면 이 PR에서는 신청서를 제외하고 동아리 카드와 동아리 홍보 모달만 다루는 걸로 하는 거 어때요?

**Comment by uhmseohun** [comment]
> > 아 그건 맞는데 신청서만큼은 개별 페이지로 빼는 게 좋을 것 같아서요😇
> 
> 그러면 이 PR에서는 신청서를 제외하고 동아리 카드와 동아리 홍보 모달만 다루는 걸로 하는 거 어때요?

찬성합니당

**Comment by junhoyeo** [comment]
동아리 홍보 모달은 따로 분리해 주시고, 카드 안에서 호출만 해주시면 되겠네요
