### ISSUE TITLE
Github Action connect for Deploy - Frontend

### ISSUE THREAD

**Issue by cokia** [dimigoin/dimigoin-front-v2#25]
지금 바로 작업해두겠습니다 :) 
프로덕션 브랜치에 머지/커밋되는 것을 기준으로,
yarn
yarn build 
yarn start 하고,
빌드파일 nginx 처리하고자 합니다 :) 

또한 매 배포 결과 슬랙 알림 가능하게 설정해두겠습니다 :)

**Comment by smsmsmsmin** [comment]
`yarn start` 빼주세요!

**Comment by junhoyeo** [comment]
master 브랜치를 사용하시면 돼요!

**Comment by cokia** [comment]
github action이 여러 self-hosted 러너에 대해서 엑션별로 선택을 할려면 아키텍쳐별로 선택을 해야되서 지금같이 둘다 ubuntu x64를 쓰는 환경에서는 선택이 불가능해 프로덕션과 빌드테스트를 구분할 수 가 없습니다. 그래서 모든 커밋과 머지에 대해서 제 빌드테스트 서버에서 처리를 하고,
프로덕션의 경우 빌드테스트 서버에서 특정 스크립트 실행(파이썬, 프로덕션서버와 ssh 연결해 배포)으로 프로덕션 배포를 할려고 합니다 괜찮을까요?

20년 3월 31일까지 깃허브에서 레이블로 러너 선택하는 기능을 배포한다고 하니 그 전까지만 저렇게 설정하면 될거같아요 :)

**Comment by junhoyeo** [comment]
> github action이 여러 self-hosted 러너에 대해서 엑션별로 선택을 할려면 아키텍쳐별로 선택을 해야되서 지금같이 둘다 ubuntu x64를 쓰는 환경에서는 선택이 불가능해 프로덕션과 빌드테스트를 구분할 수 가 없습니다. 그래서 모든 커밋과 머지에 대해서 제 빌드테스트 서버에서 처리를 하고,
> 프로덕션의 경우 빌드테스트 서버에서 특정 스크립트 실행(파이썬, 프로덕션서버와 ssh 연결해 배포)으로 프로덕션 배포를 할려고 합니다 괜찮을까요?
> 
> 20년 3월 31일까지 깃허브에서 레이블로 러너 선택하는 기능을 배포한다고 하니 그 전까지만 저렇게 설정하면 될거같아요 :)
> 
> -------수정-------
> [dimigoin/dimigoin-back-v2#21 (comment)](https://github.com/dimigoin/dimigoin-back-v2/issues/21#issuecomment-601745813)
> 백엔드쪽 에서 이렇게 진행하자 하시는 의견이 나와서 프론트엔드 레포쪽은 어떻게 진행하는게 좋을지 의견 한번만 부탁드리겠습니다 :) @junhoyeo

빌드테스트는 now도 있으니까 프론트는 바로 디플로이 달고 백엔드는 테스트만 달아두는 거 어때요?

**Comment by cokia** [comment]
넵 알겠습니다 선배님 :)

**Comment by junhoyeo** [comment]
라고 우영님께서 말씀하셨네요 좋아요!
