### ISSUE TITLE
[Auth] Login Page

### ISSUE THREAD

**Issue by junhoyeo** [dimigoin/dimigoin-front-v2#7]

**Comment by uhmseohun** [comment]
[https://github.com/dimigoin/dimigoin-front/issues/141#issue-419316299](https://github.com/dimigoin/dimigoin-front/issues/141#issue-419316299)
이것도 참고해서 하시면 좋을 것 같아요!

**Comment by junhoyeo** [comment]
> dimigoin/dimigoin-front#141 (comment)

로그인을 안 해도 메인페이지로 들어갈 수 있게 하라는 말씀이세요?

**Comment by uhmseohun** [comment]
> > [dimigoin/dimigoin-front#141](https://github.com/dimigoin/dimigoin-front/issues/141) (comment)
> 
> 어떤 걸 참고하라는 말씀이신지 이해가 안 돼요😥
> 로그인을 안 해도 메인페이지로 들어갈 수 있게 하는 것도 함께 구현하라는 말씀이세요?

사실 저도 저 이슈가 완벽하게 이해는 안 돼서.. 혹시 몰라서 언급한 거였어요😂ㅜㅜ

**Comment by reactericdev** [comment]
일단은 레거시에 있는 그대로 가져오도록 하겠습니다!
(정한)
